# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b83cdbe6a63d066737ff9846533d7798e2c48fcf8319c50fc5d7ff550f2c96fe840128390ed50e8a3520eead9151d477e448312aff157e424585b5fab4f6f21

test:
  secret_key_base: ae2ce0d61db349b71c18004a5ef098e539fe7daef8fe81d8cb37c43cdc821c848c94675aa9415989f513bf46b15d7174261747516e7478072d340fb5d46917a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
